### ISSUE TITLE
Parabéns pelo trabalho !!!

### ISSUE THREAD

**Issue by MFerrugem** [RaideNnigth/Z808-Feijoada#5]
Parabéns pelo trabalho pessoal. Boas férias e aproveitem o descanso !!!
P.S. Deu um belo caldo essa feijoada !!!

**Comment by RaideNnigth** [comment]
Muito obrigado! Ficamos todos orgulhosos! :D !!!!!!!!!!!

**Comment by ravilon** [comment]
Obrigado, ficamos felizes em ouvir. Aguarde o próximo projeto nosso se chamará Churrasco
